export type Role = 'PATIENT' | 'DOCTOR' | 'ADMIN' | 'STAFF';

export interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
  createdAt: string;
  isActive: boolean;
}

export interface Patient {
  id: string;
  userId: string;
  user?: User;
  age: number;
  gender: string;
  bloodGroup: string;
  weight: number;
  height: number;
  allergies: string;
  medicalHistory: string;
  familyHistory: string;
  insuranceDetails: string;
  createdAt: string;
}

export interface Doctor {
  id: string;
  userId: string;
  user?: User;
  specialization: string;
  department: string;
  experience: number;
  qualification: string;
  licenseNumber: string;
  availableSlots: string[]; // ISO timestamps
  createdAt: string;
}

export type AppointmentStatus = 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED';

export interface Appointment {
  id: string;
  patientId: string;
  patient?: Patient;
  doctorId: string;
  doctor?: Doctor;
  scheduledAt: string;
  status: AppointmentStatus;
  notes?: string;
  createdAt: string;
}

export interface EHR {
  id: string;
  patientId: string;
  doctorId: string;
  doctor?: Doctor;
  prescriptions: any; // JSON Array
  diagnosticReports: any; // JSON Array
  treatmentHistory: any; // JSON Array
  vaccinationRecords: any; // JSON Array
  updatedAt: string;
}

export interface LabReport {
  id: string;
  patientId: string;
  reportType: string;
  fileUrl: string;
  analysisResult: any; // JSON
  abnormalFlags: string[];
  uploadedAt: string;
}

export interface DiseasePrediction {
  id: string;
  patientId: string;
  symptoms: string[];
  inputs: any;
  predictedDisease: string;
  riskScore: number;
  severityLevel: string;
  modelUsed: string;
  createdAt: string;
}

export interface TreatmentRecommendation {
  id: string;
  patientId: string;
  doctorId: string;
  doctor?: Doctor;
  recommendedTreatment: any;
  suggestedTests: string[];
  medicationGuidance: any;
  createdAt: string;
}

export interface PatientOutcome {
  id: string;
  patientId: string;
  recoveryProbability: number;
  icuRequired: boolean;
  readmissionRisk: number;
  mortalityRisk: number;
  expectedStayDays: number;
  createdAt: string;
}

export type WardType = 'GENERAL' | 'ICU' | 'EMERGENCY' | 'PRIVATE';

export interface Bed {
  id: string;
  wardType: WardType;
  isOccupied: boolean;
  patientId: string | null;
  patient?: Patient;
  reservedUntil: string | null;
}

export interface StaffSchedule {
  id: string;
  userId: string;
  user?: User;
  shiftStart: string;
  shiftEnd: string;
  role: string;
  department: string;
  autoGenerated: boolean;
}

export type ResourceType = 'VENTILATOR' | 'OXYGEN' | 'EQUIPMENT';

export interface Resource {
  id: string;
  resourceType: ResourceType;
  totalUnits: number;
  availableUnits: number;
  lastUpdated: string;
}

export type AlertType = 'CRITICAL' | 'EMERGENCY' | 'MEDICATION' | 'LAB_REPORT';

export interface Alert {
  id: string;
  patientId: string;
  patient?: Patient;
  alertType: AlertType;
  message: string;
  isResolved: boolean;
  notifiedAt: string;
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  body: string;
  channel: 'EMAIL' | 'SMS' | 'WHATSAPP' | 'PUSH';
  sentAt: string;
  isRead: boolean;
}

export interface ChatSession {
  id: string;
  userId: string;
  messages: Array<{ role: 'user' | 'bot'; content: string; intent?: string; suggestedActions?: string[] }>;
  createdAt: string;
  updatedAt: string;
}
